version: "3.9"

services:
  # Mongodb service
  mongo_db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}
